import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const customFont = localFont({
  src: [
    {
      path: "../public/fonts/Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-custom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${customFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
